apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: simple-api
        image: dillonad/simple-api:latest
        ports:
        - containerPort: 5000
          protocol: tcp